# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppINSSH <- function(d, s) {
    .Call(`_sshicm_RcppINSSH`, d, s)
}

RcppINSSHICM <- function(d, s, seed, permutation_number) {
    .Call(`_sshicm_RcppINSSHICM`, d, s, seed, permutation_number)
}

RcppICSSH <- function(d, s, bin_method = "Sturges") {
    .Call(`_sshicm_RcppICSSH`, d, s, bin_method)
}

RcppICSSHICM <- function(d, s, seed, permutation_number, bin_method = "Sturges") {
    .Call(`_sshicm_RcppICSSHICM`, d, s, seed, permutation_number, bin_method)
}

