# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IC_SSH <- function(d, s, bin_method) {
    .Call(`_sshicm_IC_SSH`, d, s, bin_method)
}

IC_SSHICM <- function(d, s, permutation_count, seed, bin_method = "SquareRoot") {
    .Call(`_sshicm_IC_SSHICM`, d, s, permutation_count, seed, bin_method)
}

