# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IC_SSH <- function(d, s, bin_method) {
    .Call(`_sshicm_IC_SSH`, d, s, bin_method)
}

IC_SSHICM <- function(d, s, seed, permutation_number, bin_method = "Sturges") {
    .Call(`_sshicm_IC_SSHICM`, d, s, seed, permutation_number, bin_method)
}

IN_SSH <- function(d, s) {
    .Call(`_sshicm_IN_SSH`, d, s)
}

